### ISSUE TITLE
Limit/filter by visibility of toots?

### ISSUE THREAD

**Issue by rugk** [hughrun/ephemetoot#16]
Use case: Cleanup only "private" toots, leaving public toots intact.

I only want to delete toots, that are non-public, i.e. unlisted, followers-only or a DM.

Could you integrate this filter? Maybe just as a config option "keep public toots"? (Or more elaborate by listing the visibility styles to delete.)

----

[Mastopurge does not support it either](https://github.com/ThomasLeister/mastopurge/issues/21) and [I'm still searching for a solution](https://social.wiuwiu.de/@rugk/103793160110316089). :smiley:

**Comment by hughrun** [comment]
Hi @rugk I'm working on another project right now but will take a look at this in a couple of weeks. Should be reasonably easy to do with a flag.
