### ISSUE TITLE
Use virtualenv

### ISSUE THREAD

**Issue by rugk** [hughrun/ephemetoot#17]
You could use Pythons virtualenv for an easier setup and development.

**Comment by hughrun** [comment]
I plan to rearrange things a bit to use `setuptools` over Easter. Will check out what `virtualenv` can do to make things easier also.

**Comment by hughrun** [comment]
Seems like this is up to the user rather than the package.

**Comment by rugk** [comment]
nah you should define your deps etc. in there (dunno the detals though, I'm not a pYTHON DEV)
