### ISSUE TITLE
BUG - "Unknown ERROR 'toots_to_keep'"

### ISSUE THREAD

**Issue by rootwyrm** [hughrun/ephemetoot#21]
Running into a rather unusual issue.

Checking 252 toots...
🛑 Unknown ERROR deleting toot - 104119721104732502
'toots_to_keep'
🛑 Unknown ERROR deleting toot - 104118409476636157
'toots_to_keep'
🛑 Unknown ERROR deleting toot - 104117448639448175
'toots_to_keep'
...
📌 skipping pinned toot - 103499629853797922
📌 skipping pinned toot - 102981316242187388
....
Removed 0 toots.

---------------------------------------
🥳 ==> 🧼 ==> 😇 User cleanup complete!

At first I thought this was a config.yaml issue, but it continues to persist with changes to the config. It's clearly not a token issue, since this token worked with the old ephemetoot and can clearly still retrieve all of the toots. 

Environment is FreeBSD 12.1 using a Python 3.7 virtualenv (to avoid issues with modules.)

**Comment by hughrun** [comment]
hmm that does look like it's probably an error in your config. Are you able to show me what your `config.yaml` file looks like? (without the access token!)

**Comment by rootwyrm** [comment]
Ah-ha, so it is... did some more fussing, and it's choking if you don't have _everything_ present, instead of assuming 'absent = unset or null.' Which seems to me should be considered a bug, particularly since the error message isn't enlightening.

```
  days_to_keep : 30
  keep_pinned : True
  toots_to_keep :
  hashtags_to_keep : !!set { }
  visibility_to_keep :
    - direct
```

Results in the same 'Unknown ERROR'

```
  toots_to_keep :
    -
```
Behaves as expected.

```
  hashtags_to_keep :
    -
```
Results in:
🛑 Unknown ERROR deleting toot - 104085338364800829
'list' object has no attribute 'intersection'

... where one would reasonably assume it to follow the same scheme as the other elements, instead of something completely different.

**Comment by hughrun** [comment]
hmm yes that's probably a reasonable expectation. `hashtags_to_keep` needs to be a Set rather than a List so we can use an intersection but I can change the code so it initially takes a list and turns it into a Set. Probably also should set some default empty values if something is absent.
