### ISSUE TITLE
Date/time stamp, Rate Limiting, Retry-After Display

### ISSUE THREAD

**Issue by amarand** [hughrun/ephemetoot#22]
All of these suggestions would likely be options that can be turned on and off either on the command line and/or in the configuration file: (Not everyone wants these things, I imagine.)

I'd love to see an option to include a date/time stamp at the beginning of each action in the log-file. I'm running this script for about 30 days straight, due to rate limiting, to delete around 45k toots, and I'd like to see when each thing happened. I would especially like to see a date/time stamp for each action ("deleted"/"unboosted") but also for any errors (like rate limiting) so I can easily see when things are happening.

Also, as the Mastodon Core seems to have its API rate limited to 30 deletes per 30 minute period (or something like that), it might be nice to have a "slow down" rate limiting option so you can delete continuously, without causing your social media connection to also get throttled.

Also, I believe API rate limiting has a feature called Retry-After, and I'm wondering if that could be (optionally) displayed along with the "Rate Limited" error message?

**Comment by hughrun** [comment]
These all sounds sensible. 

Timestamp should be reasonably simple to do and I agree would be useful. You're right re the API rate limiting - the low rate is a bit controversial but out of our hands. I think Mastodon.py does give us the option to 'slow down' as you describe, I'll have to look into it.

**Comment by amarand** [comment]
Awesome, thanks for looking at these enhancements!
