### ISSUE TITLE
Requesting --version switch

### ISSUE THREAD

**Issue by amarand** [hughrun/ephemetoot#27]
**Is your feature request related to a problem? Please describe.**
I went to upgrade to the latest version (Wow, that was so fast! Thank you! Do you have a Kofi or Paypal or something?) and I realized I have no idea which version I'm running at any given point. It would be nice to be able to run --version and see which version it is.

**Describe the solution you'd like**
--version displays current version of application

**Describe alternatives you've considered**
grepping for the version in the source code.

**Additional context**
Fairly simple request.

**Comment by hughrun** [comment]
Hmm good idea.

You can get the version number with `pip show ephemetoot` however I've just realised that I didn't update the version number in setuptools so it will say version 2.1.0 for everything after 2.1.0. Whoops.

I'll look at a way to do this with a simple `--version` flag.
