### ISSUE TITLE
BUG - 

### ISSUE THREAD

**Issue by amarand** [hughrun/ephemetoot#28]
**Describe the bug**
Pulled down the latest version, created a new directory, git, copied configuration file over, ran with --pace and -datestamp and noticed that neither datestamps were shown, and the pacing did not throttle back to 30 per minute to avoid rate limit.

**To Reproduce**
Running the following script from the freshly downloaded ephemetoot (with git):

python3 ephemetoot --pace --datestamp

This is in a fresh directory. Old directory renamed. Verified this is the correct version by running --help, which displays properly.

**Expected behavior**
Expect rate throttled back to one per minute, and date stamps to display (for each line?)

**Screenshots**

**Environment (please complete the following information):**
 - OS: Raspian 4.19.95-v7+
 - Python version 3.7.3

**Additional context**

**Comment by hughrun** [comment]
Hi @amarand . You should not need to use the `python3` command if you (re)installed ephemetoot using pip. Can you please try:
```
pip3 install .
ephemetoot --pace --datestamp
```

**Comment by amarand** [comment]
Ahh, that fixed the issue, thank you! I need to learn pip3/git a little better. Thanks for the assist!
