### ISSUE TITLE
"FileNotFoundError" when running script

### ISSUE THREAD

**Issue by jneplokh** [hughrun/ephemetoot#36]
**Description**
When running ephemetoot, after "fetching account details," the program fails with a FileNotFoundError in ~/toots_archive/TOOT.json, a DM, and I would like to exclude DMs. 

**Environment:**
 - MacOS 10.15.5 Catalina
 - Python 3.8

**To Reproduce**
Run the installation instructions and configure the config.yaml as told. 

**Expected behavior**
The script to fetch account details and go on to delete the toots. 

**Actual behavior**
As stated, the script fails as it says that toot file cannot be found and fails. Full read and write access is given as well. 

**Output**
```
Traceback (most recent call last):
  File "/usr/local/bin/ephemetoot", line 92, in <module>
    ephemetoot.checkToots(user, options)
  File "/usr/local/lib/python3.8/site-packages/lib/ephemetoot.py", line 366, in checkToots
    checkBatch(timeline)
  File "/usr/local/lib/python3.8/site-packages/lib/ephemetoot.py", line 112, in checkBatch
    with open(filename, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/toots_archive/TOOT.json'
```
**Additional Information**
When I remove the `archive` option and run `ephemetoot --test` it works just fine, but I would really like to archive my toots, of course.

**Comment by hughrun** [comment]
Thanks for this bug report. I'll look into it over the weekend.

Can I just check: 

1. are you _additionally_ requesting a feature of being able to exclude DMs from being archived?
2. is `TOOT.json` the actual file name or are you just calling it that for the purposes of this bug report?

It would be great if you could post your config file (**without** the `access_token`)

**Comment by jneplokh** [comment]
Hey, thanks for the quick response too! 

1. Oh sorry, let me clarify, What I mean is in my config (which I will add), I have `direct` being set to keep. The error it gives though says TOOT.json cannot be found. That toot is a direct message, though, so it shouldn't be archived at all since it should not be getting deleted.
2. `TOOT.json` is not the file name, but I am just referring to it for the purposes of this bug report.

Here is my `config.yaml` without the `access_token`, of course:

```
  username : jacobneplokh
  base_url : fosstodon.org
  days_to_keep : 90
  keep_pinned : true
  toots_to_keep :
    - 104493393446556167
    - 104493412092227272
    - 104495912296386229
  hashtags_to_keep : 
    - 100DaysToOffload
  visibility_to_keep :
    - direct
    - private
  archive : ~/toots_archive/
```

**Comment by hughrun** [comment]
Ok I see the problem, will update in the next few days: the example config actually doesn't work! It's an issue with tilde expansion.

FYI as currently implemented,  if you set a value for `archive` it will archive all toots regardless of whether they are being deleted or not. I could maybe make a flag so you can optionally only archive toots that are being deleted - you could add an enhancement issue if you would like this.

**Comment by jneplokh** [comment]
> the example config actually doesn't work! It's an issue with tilde expansion.

Ah, ok. Is there a config I can use for now before it is fixed?

> you could add an enhancement issue if you would like this.

This would be nice to have, so I will add an enhancement issue.

Thank you so much!

**Comment by hughrun** [comment]
Sorry, the documentation for this feature needs a bit of work.

Currently you need to use a full filepath.

You're trying to save to a folder called `toots_archive`, which needs to exist and be a sibling of your `Documents` and `Desktop` directories. It will be something like: `/Users/jacob/toots_archive`. To get the full path run:

`cd ~/toots_archive && pwd`

The filepath you need to use should print to the screen - you just need to add an `/` to the end.

**Comment by jneplokh** [comment]
No worries, I had actually tried it myself and using the full, absolute file path made it work 👍
