### ISSUE TITLE
BUG - Typo in Config Documentation

### ISSUE THREAD

**Issue by jneplokh** [hughrun/ephemetoot#39]
**Description**
I was reading back through the docs to see how to update, and while skimming I noticed I typo in the [Configuration file docs](https://github.com/brave/brave-browser/issues/8187). When describing copying `example-config.yaml` it currently says 

`cp example-config.yam config.yaml`

while it should say

`cp example-config.yaml config.yaml`, of course.

Nothing too major, but just in case someone does not notice the error should they copy & paste. This is extremely simple, so I can make a PR if you would like. Only a letter :P

**Comment by hughrun** [comment]
oh LOL whoops.

Do you mind sending a PR?

**Comment by jneplokh** [comment]
Yep, just sent the PR

**Comment by hughrun** [comment]
thanks!
