### ISSUE TITLE
BUG - v2.6 still shows v2.5

### ISSUE THREAD

**Issue by amarand** [hughrun/ephemetoot#44]
**Description**

After upgrading, getting the older version displaying, and then doing a full uninstall/reinstall, getting v2.5 in header instead of v2.6:

============= EPHEMETOOT v2.5 ================

**Environment (please complete the following information):**
Current Raspian
Python 2.7

**To Reproduce**

./ephemetoot --datestamp --pace --retry-mins 5

**Expected behavior**
Header should show proper version (v2.6)

**Actual behavior**
Header displays "v2.5"

**Screenshots**

**Additional context**

pip uninstall ephemetoot
cd ..
rm -rf ephemetoot/
git clone https://github.com/hughrun/ephemetoot.git
cd ephemetoot
git checkout master

$ pip install .
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /home/amarand/ephemetoot
Requirement already satisfied: Mastodon.py in /home/amarand/.local/lib/python2.7/site-packages (from ephemetoot==2.6) (1.5.1)
Requirement already satisfied: pyyaml in /home/amarand/.local/lib/python2.7/site-packages (from ephemetoot==2.6) (5.3.1)
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from ephemetoot==2.6) (2.21.0)
Requirement already satisfied: blurhash>=1.1.4 in /home/amarand/.local/lib/python2.7/site-packages (from Mastodon.py->ephemetoot==2.6) (1.1.4)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from Mastodon.py->ephemetoot==2.6) (1.12.0)
Requirement already satisfied: python-magic in /home/amarand/.local/lib/python2.7/site-packages (from Mastodon.py->ephemetoot==2.6) (0.4.18)
Requirement already satisfied: decorator>=4.0.0 in /home/amarand/.local/lib/python2.7/site-packages (from Mastodon.py->ephemetoot==2.6) (4.4.2)
Requirement already satisfied: python-dateutil in /home/amarand/.local/lib/python2.7/site-packages (from Mastodon.py->ephemetoot==2.6) (2.8.1)
Requirement already satisfied: pytz in /home/amarand/.local/lib/python2.7/site-packages (from Mastodon.py->ephemetoot==2.6) (2020.1)
Building wheels for collected packages: ephemetoot
  Running setup.py bdist_wheel for ephemetoot ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-tIelrK/wheels/a5/17/aa/24a4cb71e1e04e01c8c977ce1c50c043e2377f1ff1d6be57ba
Successfully built ephemetoot
Installing collected packages: ephemetoot
Successfully installed ephemetoot-2.6

**Comment by hughrun** [comment]
Hi

Looks like you originally installed this with `pip3` (Python 3) and you are trying to reinstall it with `pip` (Python 2). So your PATH is actually looking at the original install. `ephemetoot` only runs with Python 3. Try:
```
git checkout v2.6
pip3 install .
```

**Comment by amarand** [comment]
Awesome, that fixed the issue, thank you!

I'm sorry that I'm a little new to pip versus pip3.

Wanted to let you know that I was able to successfully purge tens of thousands of toots, and it just finished today!

Now I get to see if i can get this to run as a daily cronjob.

**Comment by hughrun** [comment]
Great news and no problem - it can get confusing.

I'm working on publishing this to pypi so soon upgrading should be easier.
