### ISSUE TITLE
Quieter mode?

### ISSUE THREAD

**Issue by msafadieh** [hughrun/ephemetoot#56]
**Does your proposal relate to...**

- [ ] documentation
- [x] what is displayed when running ephemetoot
- [ ] a new config value
- [X] a new flag (option)
- [ ] something else

**Is your feature request related to a problem? Please describe.**
I run ephemetoot in a crontab, which means I get an email each time one of my scripts has any output. It would be cool if there was an option to completely suppress output when zero toots are deleted (since nothing changed).

**Describe the solution you'd like**
The behavior of `--quiet` could be modified to:
- not print `Fetching account details for X`
- only print `Removed X toots` when X > 0

Alternative, we could have a "--silent" or "-qq" (as in double quiet) flag but that could be confusing.

**Would like to write the code yourself?**

- [X] I would like to write the code myself and then log a pull request
- [ ] I would like someone else to write the code
- [ ] I would like someone to help me write the code

**Describe alternatives you've considered**
I can just wrap ephemetoot in a shell script that parses the output and only prints it out if the number of deleted toots is greater than zero.

```
ephemetoot --quiet -c config.yaml | grep "Removed [1-9][0-9]* toots."
```

**Comment by hughrun** [comment]
Hi @msafadieh and thanks for the suggestion.

I can understand your use-case, and to be honest didn't give a huge amount of thought to `--quiet` other than "less logging might be nice sometimes". My instinct is to avoid changing behaviour where some people may be relying on the current behaviour, but I think you've raised some useful points. The concerns I would have with changing the behaviour of the current flag as you described are:

1. users with multiple accounts in their config likely want to know which account the deletes refer to.
2. some users may like the reassurance that the script ran as scheduled, even if it didn't delete anything

However you're right that it never really needs two lines in a quiet mode. So my ideal solution (if you have the time/inclination) would be to kind of split the difference:

### `-q`

Always prints one line:
```
Removed X toots for account user@example.social
```

### `-qq`
```python
# Only prints to console/log if X > 0
```
And I guess if we took it to its logical conclusion, there's potential for:

### `-qqq`

Never prints anything
