### ISSUE TITLE
add boosts only option

### ISSUE THREAD

**Issue by wgahnagl** [hughrun/ephemetoot#61]
**Does your proposal relate to...**

- [ ] documentation
- [ ] what is displayed when running ephemetoot
- [x] a new config value
- [x] a new flag (option)
- [ ] something else

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. e.g. _I'm always frustrated when [...]_

I just want to be able to clear out my account from posts that I've boosted

**Describe the solution you'd like**

I can use ephemetoot to remove only boosted toots and nothing else

**Would like to write the code yourself?**

- [x] I would like to write the code myself and then log a pull request
- [ ] I would like someone else to write the code
- [ ] I would like someone to help me write the code

**Describe alternatives you've considered**

**Additional context**

https://github.com/wgahnagl/ephemetoot/tree/add-boosts-only
I've got it working (and deleting toots on my mastodon account right now lol)
I'll write tests for it when I get back home tomorrow and open a PR! :ok_hand:

**Comment by hughrun** [comment]
sweet I'll take a look

**Comment by hughrun** [comment]
Nice and simple, looks good as far as I can see.

**Comment by wgahnagl** [comment]
oh man, I totally let this dissolve into the nether lol 
I still need to write those tests, but things have gotten really busy for me!

**Comment by hughrun** [comment]
Haha all good, it's certainly been a year. I'll leave this open and when you have time to get to it looking forward to your PR 😀

**Comment by nunesgh** [comment]
Hi!
Thank you @hughrun and @wgahnagl for working on this feature!

Are there plans to add this feature to the tool?

**Comment by hughrun** [comment]
@nunesgh there hasn't been much action on ephemetoot recently (Mastodon releasing built-in deletion of posts with limited control has reduced the need for such a tool for many people) but I'll take a look at this soon and see if we can get it into the tool.
