### ISSUE TITLE
Include tests on pypi distribution

### ISSUE THREAD

**Issue by pacoesteban** [hughrun/ephemetoot#62]
**Does your proposal relate to...**

- [ ] documentation
- [ ] what is displayed when running ephemetoot
- [ ] a new config value
- [ ] a new flag (option)
- [X] something else

**Is your feature request related to a problem? Please describe.**
Not really, it's a "nice to have".
I maintain the OpenBSD port of ephemetoot, and it would be nice to have the tests included on the pypi distribution.

**Describe the solution you'd like**
Just that, having the tests included on the pypi distribution.  It makes it easier for us to asses that and update does not break the port.

**Would like to write the code yourself?**

- [ ] I would like to write the code myself and then log a pull request
- [X] I would like someone else to write the code
- [ ] I would like someone to help me write the code

**Describe alternatives you've considered**

**Additional context**

**Comment by hughrun** [comment]
Oh, I didn't realise they weren't included! I'm pretty new to PyPi. Will investigate.

Also thanks for making a port 😀

**Comment by hughrun** [comment]
This will be included in the next release.
