### ISSUE TITLE
Mention cleantoots in the docs

### ISSUE THREAD

**Issue by Crocmagnon** [hughrun/ephemetoot#71]
**Does your proposal relate to...**

- [x] documentation

**Proposal**
Hello ! 👋🏻

I’m the author of `cleantoots`, a similar CLI program to delete your old toots.

I just randomly came across this project and it looks like we both had the same idea except in different timelines 😊

Would you be open to linking to cleantoot’s project page in your readme? Perhaps in a “Similar projects” or “See also” section?

I just did so myself (I don’t expect anything in return of course, I just find your project cool 😊): https://git.augendre.info/gaugendre/cleantoots

Anyway, have fun!

**Comment by hughrun** [comment]
Oh nice one! I'm happy to add something to the README.

**Comment by Crocmagnon** [comment]
Thanks! 😃
