### ISSUE TITLE
Optionally include media attachments in archives

### ISSUE THREAD

**Issue by fobser** [hughrun/ephemetoot#72]
**Does your proposal relate to...**

- [ ] documentation
- [ ] what is displayed when running ephemetoot
- [X] a new config value
- [ ] a new flag (option)
- [ ] something else

**Is your feature request related to a problem? Please describe.**
The archive option stores the json representation of a toot on disk.
The media_attachments array contains a list of URIs that point to fediverse server.
Once a toot is deleted media_attachments are deleted as well and are then lost.

**Describe the solution you'd like**
I would like to fetch the media attachments and store them alongside the json of the toot.
It is probably best to replicate the directory structure the servers uses, for example I see
`https://SERVER/media_attachments/files/000/718/385/original/IMAGE.png`
The file `IMAGE.png` should be stored in the directory `media_attachments/files/000/718/385/original` below the archive path.
This would be configurable by a new archive_media [yes/no] option.

**Would like to write the code yourself?**

- [X] I would like to write the code myself and then log a pull request
- [ ] I would like someone else to write the code
- [ ] I would like someone to help me write the code

**Comment by hughrun** [comment]
Sounds great!
