### ISSUE TITLE
Remove favorites

### ISSUE THREAD

**Issue by L041S** [hughrun/ephemetoot#84]
**Does your proposal relate to...**

- [ ] documentation
- [ ] what is displayed when running ephemetoot
- [ ] a new config value
- [ ] a new flag (option)
- [x] something else

**Is your feature request related to a problem? Please describe.**
The script works great for deleting toots, it could be interesting to add an option to delete favorites as well, older than x days 

**Describe the solution you'd like**
Maybe an option in config.yaml like delete_favs: true or false ?

**Would like to write the code yourself?**

- [ ] I would like to write the code myself and then log a pull request
- [x] I would like someone else to write the code
- [ ] I would like someone to help me write the code

**Comment by hughrun** [comment]
`ephemetoot` is now in maintenance mode. I won't be adding any new features, sorry.
